version: '3.8'

services:
  php:
    container_name: meu_servidor_php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    depends_on:
      - mysql

  mysql:
    container_name: meu_servidor_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Modelagem/Projeto_Fisico.sql:/docker-entrypoint-initdb.d/Projeto_Fisico.sql:ro
volumes:
  mysql-data: